### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/notesnook#1]
Hi @c4ssiopei4, We need to adjust a few things first to move forward, OK? ✨

First, we need to adjust the `readme.md` to match [our template's default](https://github.com/dracula/template).

I ask that these changes be standardized with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would also like to contribute! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by c4ssiopei4** [comment]
Hi @luxonauta 

I adapted the repo to the templates default.

**Comment by luxonauta** [comment]
Thanks! 💜
